version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/workspace
    working_dir: /workspace
    command: dotnet watch run --project backend.csproj
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000