@backend_HostAddress = http://localhost:5000

POST {{backend_HostAddress}}/generateQuiz
Accept: application/json
Content-Type: application/json

{
  "paragraph": "This is the paragraph from which quiz questions will be generated."
}
