name: Flutter CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'

    - name: Change directory to frontend
      run: cd frontend

    - name: Install dependencies
      working-directory: frontend
      run: flutter pub get

    - name: Run lint checks
      working-directory: frontend
      run: flutter analyze

